In [1]:
import numpy as np

# Create a 1D array

arr1 = np.array([1,2,3])

print(arr1)

[1 2 3]


In [2]:
# check the array

print(type(arr1))

<class 'numpy.ndarray'>


In [3]:
# Check the shape of the array

print(arr1.shape)

(3,)


In [4]:
# accessing elements from the array

arr1[2]

3

In [5]:
# Change an element from the array

arr1[2]= 5

In [6]:
arr1

array([1, 2, 5])

In [7]:
# Create a 2D array

arr2 = np.array([[1,2,3], [4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [8]:
# Check the shape of the array

print("The shape is 2 rows and 3 columns:", arr2.shape)

The shape is 2 rows and 3 columns: (2, 3)


In [9]:
# Accessing elements from the array

arr2[0][2]

3

In [10]:
arr2[0,2]

3

In [11]:
arr2[0,-2]

2

In [12]:
arr2[0,-1]

3

In [13]:
arr2[-1, 0]

4

In [14]:
# Array of type string

arr3 = np.array(['India', 'China', 'USA' , 'Mexico'])
print(arr3)

['India' 'China' 'USA' 'Mexico']


In [15]:
arr3[1]

'China'

In [16]:
# Array of evenly spaced values within a specified interval

arr = np.arange(0, 20, 2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [17]:
# Array of evenly spaced number in a specified interval

arr = np.linspace(0, 10, 20)
print(arr)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [18]:
# Array of random values between 0 and 1 in a given shape

arr = np.random.rand(10)
print(arr)
print('\n')
arr = np.random.rand(3,4)
print(arr)

[0.92983529 0.77401837 0.88446233 0.30351856 0.90618958 0.73211001
 0.8076217  0.19673348 0.94749083 0.88401531]


[[0.15043795 0.94174252 0.82385856 0.54120723]
 [0.99500763 0.28167029 0.8607064  0.29147417]
 [0.21299199 0.95306831 0.96095294 0.68317253]]


In [19]:
# Array of zeros

print(np.zeros(10))
print('\n')
print(np.zeros((2,3)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


[[0. 0. 0.]
 [0. 0. 0.]]


In [20]:
print(np.ones((3,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [21]:
# Array of constant values in a given shape

print(np.full((4,6),10))

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]


In [22]:
# Create an array by repetition
# epeat each element of an array by a specified number of times

arr = [0, 1, 2]
print(np.repeat(arr, 3)) 

[0 0 0 1 1 1 2 2 2]


In [23]:
# Repeat an array by a specified number of times

arr = [0, 1, 2]
print(np.tile(arr, 3))

[0 1 2 0 1 2 0 1 2]


In [24]:
# Create an idenity matrix

identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [26]:
# Create a matrix with a specified diagonal array

arr = np.diag([1,2,3,4,5])
print(arr)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [27]:
arr = np.random.rand(5,5)
print(arr)

[[0.39051567 0.66837228 0.56709081 0.96414913 0.62413689]
 [0.87459063 0.62556704 0.18910953 0.91063039 0.43761323]
 [0.45277488 0.26569101 0.90261837 0.78692454 0.93150875]
 [0.62707543 0.89610395 0.71982589 0.55175428 0.28163528]
 [0.49669082 0.14214606 0.81434484 0.32786015 0.60804966]]


In [28]:
# Extract the diagonal elements in the array
print(np.diag(arr))

[0.39051567 0.62556704 0.90261837 0.55175428 0.60804966]


In [29]:
# Display the length of the array
print(len(arr))

5


In [30]:
# Display the dimension of the array
print(arr.ndim)

2


In [31]:
# Display the size of the elements
print(arr.size)

25


In [32]:
# print 4 random integers

print(np.random.randint(-10, 10, 4))

[-4 -4  6 -1]


In [33]:
# Mathematical operations

print(arr + 10)
print('\n')
print(arr - 10)
print('\n')
print(arr * 10)
print('\n')
print(arr / 10)

[[10.39051567 10.66837228 10.56709081 10.96414913 10.62413689]
 [10.87459063 10.62556704 10.18910953 10.91063039 10.43761323]
 [10.45277488 10.26569101 10.90261837 10.78692454 10.93150875]
 [10.62707543 10.89610395 10.71982589 10.55175428 10.28163528]
 [10.49669082 10.14214606 10.81434484 10.32786015 10.60804966]]


[[-9.60948433 -9.33162772 -9.43290919 -9.03585087 -9.37586311]
 [-9.12540937 -9.37443296 -9.81089047 -9.08936961 -9.56238677]
 [-9.54722512 -9.73430899 -9.09738163 -9.21307546 -9.06849125]
 [-9.37292457 -9.10389605 -9.28017411 -9.44824572 -9.71836472]
 [-9.50330918 -9.85785394 -9.18565516 -9.67213985 -9.39195034]]


[[3.90515673 6.68372276 5.67090811 9.64149129 6.24136885]
 [8.74590626 6.25567038 1.89109529 9.10630392 4.37613233]
 [4.5277488  2.65691009 9.02618374 7.86924539 9.31508749]
 [6.27075434 8.9610395  7.1982589  5.51754284 2.8163528 ]
 [4.96690819 1.42146063 8.14344837 3.27860147 6.08049656]]


[[0.03905157 0.06683723 0.05670908 0.09641491 0.06241369]
 [0.08745906 

In [34]:
# Exponentiation

print(np.exp(arr))

[[1.47774263 1.95105895 1.7631303  2.62255525 1.86663414]
 [2.39789346 1.86930562 1.20817327 2.48588912 1.54900569]
 [1.57267011 1.30433197 2.46605171 2.19663038 2.538336  ]
 [1.8721274  2.45003902 2.05407554 1.73629631 1.32529527]
 [1.64327437 1.15274501 2.25769603 1.38799484 1.83684542]]


In [35]:
# Natural logarithm

print(np.log(arr))

[[-0.94028717 -0.40290996 -0.56723583 -0.0365093  -0.47138557]
 [-0.13399936 -0.46909678 -1.66542891 -0.09361818 -0.82641979]
 [-0.79236023 -1.32542127 -0.10245543 -0.23962292 -0.0709497 ]
 [-0.46668844 -0.10969886 -0.32874592 -0.59465247 -1.26714238]
 [-0.69978754 -1.95090014 -0.20537137 -1.11516814 -0.49749873]]


In [36]:
# Base 2 logarithm

print(np.log2(arr))

[[-1.35654764 -0.5812762  -0.81834832 -0.05267178 -0.68006562]
 [-0.19332021 -0.6767636  -2.40270604 -0.13506249 -1.19227173]
 [-1.14313418 -1.91217869 -0.14781195 -0.3457028  -0.10235878]
 [-0.67328909 -0.158262   -0.4742801  -0.85790217 -1.82810002]
 [-1.00958001 -2.81455395 -0.29628826 -1.60884755 -0.71773895]]


In [37]:
# Base 10 logarithm

print(np.log10(arr))

[[-0.40836153 -0.17498157 -0.24634739 -0.01585579 -0.20472015]
 [-0.05819518 -0.20372614 -0.72328659 -0.04065786 -0.35890955]
 [-0.34411768 -0.57562314 -0.04449583 -0.10406691 -0.03081306]
 [-0.20268021 -0.04764161 -0.14277254 -0.25825429 -0.55031294]
 [-0.30391387 -0.84726516 -0.08919165 -0.48431137 -0.21606095]]


In [38]:
# sin function

print(np.sin(arr))

[[0.38066532 0.61970932 0.53718052 0.82156412 0.5843971 ]
 [0.76728103 0.58555703 0.18798437 0.78989048 0.42377882]
 [0.43746249 0.26257609 0.78495183 0.70818527 0.80252101]
 [0.58677911 0.78089915 0.65925377 0.52418199 0.27792687]
 [0.47651884 0.14166786 0.72727609 0.3220179  0.57126778]]


In [39]:
print(np.sin(180))

-0.8011526357338306


In [40]:
print(np.sin(0))

0.0


In [41]:
# cos function

print(np.cos(arr))

[[0.92471288 0.78483142 0.8434673  0.57011613 0.81146782]
 [0.64131102 0.81063122 0.98217202 0.61324793 0.9057657 ]
 [0.89923666 0.96491129 0.6195568  0.70602665 0.59662386]
 [0.80974704 0.62465712 0.75192052 0.85160627 0.96060223]
 [0.87916426 0.98991425 0.68634502 0.94673358 0.82076375]]


In [42]:
print(arr)

[[0.39051567 0.66837228 0.56709081 0.96414913 0.62413689]
 [0.87459063 0.62556704 0.18910953 0.91063039 0.43761323]
 [0.45277488 0.26569101 0.90261837 0.78692454 0.93150875]
 [0.62707543 0.89610395 0.71982589 0.55175428 0.28163528]
 [0.49669082 0.14214606 0.81434484 0.32786015 0.60804966]]


In [43]:
# sum along the row
print(np.sum(arr, axis=0))

[2.84164743 2.59788034 3.19298944 3.54131849 2.8829438 ]


In [44]:
# sum along the column
print(np.sum(arr, axis=1))

[3.21426477 3.03751082 3.33951755 3.07639484 2.38909152]


In [45]:
# minimum item value along the row
print(np.min(arr))

0.1421460630520005


In [46]:
print(np.max(arr))

0.9641491288373221


In [47]:
# calculate the overall mean

print(np.mean(arr))

0.602271180206397


In [48]:
# calculate the mean along the row

print(np.mean(arr, axis=0))

[0.56832949 0.51957607 0.63859789 0.7082637  0.57658876]


In [49]:
# calculate the median
print(np.median(arr))

0.6241368853550862


In [50]:
# calculate the standard deviation
print(np.std(arr))

0.24224976717123525


In [51]:
# calculate the variance
print(np.var(arr))

0.058684949694517693


In [52]:
print(arr)
print('\n')
print(arr[1:3, 2:5])

[[0.39051567 0.66837228 0.56709081 0.96414913 0.62413689]
 [0.87459063 0.62556704 0.18910953 0.91063039 0.43761323]
 [0.45277488 0.26569101 0.90261837 0.78692454 0.93150875]
 [0.62707543 0.89610395 0.71982589 0.55175428 0.28163528]
 [0.49669082 0.14214606 0.81434484 0.32786015 0.60804966]]


[[0.18910953 0.91063039 0.43761323]
 [0.90261837 0.78692454 0.93150875]]


In [53]:
# Sort an array
arr = np.random.rand(5,5)
print(arr)

[[0.13246669 0.56170896 0.30286588 0.98495019 0.84546984]
 [0.85896721 0.43216302 0.12416498 0.0869192  0.05972687]
 [0.80060848 0.63576306 0.64493311 0.56099898 0.73762774]
 [0.20015441 0.66440042 0.51727431 0.04151705 0.07478443]
 [0.94708391 0.49790978 0.74775076 0.21996163 0.28548979]]


In [54]:
# sort along the column

print(np.sort(arr, axis=1))

[[0.13246669 0.30286588 0.56170896 0.84546984 0.98495019]
 [0.05972687 0.0869192  0.12416498 0.43216302 0.85896721]
 [0.56099898 0.63576306 0.64493311 0.73762774 0.80060848]
 [0.04151705 0.07478443 0.20015441 0.51727431 0.66440042]
 [0.21996163 0.28548979 0.49790978 0.74775076 0.94708391]]


In [55]:
# Transpose an array
print(arr)
print('\n')
print(arr.T)

[[0.13246669 0.56170896 0.30286588 0.98495019 0.84546984]
 [0.85896721 0.43216302 0.12416498 0.0869192  0.05972687]
 [0.80060848 0.63576306 0.64493311 0.56099898 0.73762774]
 [0.20015441 0.66440042 0.51727431 0.04151705 0.07478443]
 [0.94708391 0.49790978 0.74775076 0.21996163 0.28548979]]


[[0.13246669 0.85896721 0.80060848 0.20015441 0.94708391]
 [0.56170896 0.43216302 0.63576306 0.66440042 0.49790978]
 [0.30286588 0.12416498 0.64493311 0.51727431 0.74775076]
 [0.98495019 0.0869192  0.56099898 0.04151705 0.21996163]
 [0.84546984 0.05972687 0.73762774 0.07478443 0.28548979]]


In [56]:
print(arr.transpose())

[[0.13246669 0.85896721 0.80060848 0.20015441 0.94708391]
 [0.56170896 0.43216302 0.63576306 0.66440042 0.49790978]
 [0.30286588 0.12416498 0.64493311 0.51727431 0.74775076]
 [0.98495019 0.0869192  0.56099898 0.04151705 0.21996163]
 [0.84546984 0.05972687 0.73762774 0.07478443 0.28548979]]


In [57]:
# Flatten the 2D array

print(arr)
print('\n')
print(arr.flatten())

[[0.13246669 0.56170896 0.30286588 0.98495019 0.84546984]
 [0.85896721 0.43216302 0.12416498 0.0869192  0.05972687]
 [0.80060848 0.63576306 0.64493311 0.56099898 0.73762774]
 [0.20015441 0.66440042 0.51727431 0.04151705 0.07478443]
 [0.94708391 0.49790978 0.74775076 0.21996163 0.28548979]]


[0.13246669 0.56170896 0.30286588 0.98495019 0.84546984 0.85896721
 0.43216302 0.12416498 0.0869192  0.05972687 0.80060848 0.63576306
 0.64493311 0.56099898 0.73762774 0.20015441 0.66440042 0.51727431
 0.04151705 0.07478443 0.94708391 0.49790978 0.74775076 0.21996163
 0.28548979]


In [58]:
# Append elements to an array

arr = np.array([4,5,6,7])

In [59]:
arr1 = np.append(arr, 8)
arr1

array([4, 5, 6, 7, 8])

In [60]:
arr2 = np.append(arr, [9,10,11])
print(arr2)

[ 4  5  6  7  9 10 11]


In [61]:
# Insert elements to an array

arr3 = np.insert(arr, 0, [12,13,14])
print(arr3)

[12 13 14  4  5  6  7]


In [62]:
# Remove elements from an array

print(arr)
print('\n')
arr4 = np.delete(arr, 0)
print(arr4)

[4 5 6 7]


[5 6 7]


In [63]:
# Delete multiple elements

print(arr2)
print('\n')
arr5 = np.delete(arr2, [1,4])
print(arr5)

[ 4  5  6  7  9 10 11]


[ 4  6  7 10 11]


In [64]:
# Copy elements from an array

arr1 = np.arange(10, 40, 3)
arr1

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37])

In [65]:
arr_copy = np.copy(arr1)
arr_copy

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37])

In [66]:
arr_copy = arr1.copy()
print(arr_copy)

[10 13 16 19 22 25 28 31 34 37]


In [67]:
# Combine and split an array

arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])

In [68]:
# Combine the array items by row

cat = np.concatenate((arr1,arr2), axis=0)
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [69]:
# Combine array items by column

cat = np. concatenate((arr1, arr2), axis=1)
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [70]:
# stack arrays vertically
cat = np.vstack((arr1, arr2))
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [71]:
# Stack arrays horizontally
cat = np.hstack((arr1, arr2))
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [72]:
# Set operations

# Find elements from an array
arr = np.array([1,2,3,4,5,6,3,6,1,2,4])
print(np.unique(arr))

[1 2 3 4 5 6]


In [73]:
# return the number of times each unique item appears
arr = np.array([1,1,2,2,3,3,4,5,6])
uniques, counts = np.unique(arr, return_counts=True)
print(uniques)
print(counts)

[1 2 3 4 5 6]
[2 2 2 1 1 1]


In [74]:
# Intersection of 2 array elements

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,6,7])

In [75]:
print(np.intersect1d(arr1, arr2))

[3 4 5]


In [76]:
# Union of 2 array elements

print(np.union1d(arr1, arr2))

[1 2 3 4 5 6 7]


In [77]:
# Elements present in first array but not in the second array
print(np.setdiff1d(arr1, arr2))
print(np.setdiff1d(arr2, arr1))

[1 2]
[6 7]


In [78]:
# Elements present in either of the arrays but not both

print(np.setxor1d(arr1, arr2))

[1 2 6 7]
