In [5]:
import numpy as np

array = np.array([4,2,7,1])
temp = array.argsort(-1)
ranks = np.empty_like(temp)
ranks[temp] = np.arange(len(array))


In [6]:
ranks[temp]

array([0, 1, 2, 3])

In [7]:
temp

array([3, 1, 0, 2])

In [35]:
def arrayRankTransform(arr:int):
        d={}
        nums=sorted(list(set(arr)))
        for i in range(len(nums)):
            d[nums[i]]=i+1
        return [d[i] for i in arr]

In [36]:
arrayRankTransform([40,10,20,30])

[4, 1, 2, 3]

In [1]:
# arr = [40,10,20,30]
# d={}
# nums=sorted(list(set(arr)))
# for i in range(len(nums)):
#     d[nums[i]]=i+1
#     ls = [d[i] for i in arr]
#     print(ls)


In [41]:
aa = [1,2,3,4,5]

In [13]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6],[9,8,9]])

a,b = 0,0
for i in range(len(arr)):
    a += arr[i][i]
    print(arr[i][i])
    print(a,"->")
    print("-------------")
    b += arr[i][-i-1]
    print(arr[i][-i-1])
    print(b,"<-")
    print("-------------")
    
print("-------------")
print(abs(a-b))

1
1 ->
-------------
3
3 <-
-------------
5
6 ->
-------------
5
8 <-
-------------
9
15 ->
-------------
9
17 <-
-------------
-------------
2


In [9]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])